# travis.yml for github.com/mateidavid/fast5

dist: trusty
sudo: required
language: cpp

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential g++-4.9 libhdf5-dev libboost1.55-dev libboost-python1.55-dev python2.7-minimal libpython2.7-dev

install:
    - make -C src CXX=g++-4.9 HDF5_INCLUDE_DIR=/usr/include HDF5_LIB_DIR=/usr/lib/x86_64-linux-gnu
    - make -C python CC=gcc-4.9 CXX=g++-4.9 HDF5_INCLUDE_DIR=/usr/include HDF5_LIB_DIR=/usr/lib/x86_64-linux-gnu BOOST_INCLUDE_DIR=/usr/include BOOST_LIB_DIR=/usr/lib/x86_64-linux-gnu develop-user

script:
    - src/hdf5-mod -f file.000.fast5 && src/f5-mod file.000.fast5 && src/f5dump file.000.fast5 && src/f5dump-full file.000.fast5
    - pip list | grep fast5
    - pip show -f fast5
    - python -c 'import fast5; f = fast5.File("file.000.fast5"); print(f.file_version()); print(f.have_eventdetection_events())'
